# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-27 20:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DragNDropChangelistExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(blank=True, max_length=50)),
                ('boolean', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('order',),
                'verbose_name': "Drag n' drop changelist example",
                'verbose_name_plural': "Drag n' drop changelist example",
            },
        ),
        migrations.CreateModel(
            name='InlineExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Inline example',
                'verbose_name_plural': 'Inline example',
            },
        ),
        migrations.CreateModel(
            name='InlineExampleExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(blank=True, max_length=50)),
                ('field2', models.CharField(blank=True, max_length=50)),
                ('field3', models.CharField(blank=True, max_length=50)),
                ('inline', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='demo_application.InlineExample')),
            ],
            options={
                'verbose_name': 'One-To-One inline example',
                'verbose_name_plural': 'One-To-One inline example',
            },
        ),
        migrations.CreateModel(
            name='ModalStackedInlineExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('choice', models.CharField(choices=[(b'choice1', b'Choice 1'), (b'choice2', b'Choice 2')], max_length=20)),
                ('date', models.DateField(default=datetime.date.today)),
                ('inline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_application.InlineExample')),
            ],
            options={
                'verbose_name': 'Modal stacked inline example',
                'verbose_name_plural': 'Modal stacked inline example',
            },
        ),
        migrations.CreateModel(
            name='NestedInlineExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Nested inline',
                'verbose_name_plural': 'Nested inline',
            },
        ),
        migrations.CreateModel(
            name='PopupInlineExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('inline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_application.InlineExample')),
            ],
            options={
                'ordering': ('order',),
                'verbose_name': 'Ajax/Popup inline example',
                'verbose_name_plural': 'Ajax/Popup inline example',
            },
        ),
        migrations.CreateModel(
            name='SideBarMenuExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text=b'<strong>The affix</strong> example title. Help text may include HTML.', max_length=50)),
                ('field1', models.CharField(blank=True, max_length=50)),
                ('field2', models.CharField(blank=True, help_text=b'Small input field', max_length=50)),
                ('field3', models.CharField(blank=True, help_text=b'Medium input field', max_length=50)),
                ('field4', models.CharField(blank=True, help_text=b'Large input field (default)', max_length=50)),
                ('field5', models.CharField(blank=True, help_text=b'XLarge input field', max_length=50)),
                ('field6', models.CharField(blank=True, help_text=b'XXLarge input field', max_length=50)),
                ('field7', models.CharField(blank=True, max_length=50)),
                ('field8', models.CharField(blank=True, max_length=50)),
                ('field9', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Side-Bar menu example',
                'verbose_name_plural': 'Side-Bar menu example',
            },
        ),
        migrations.CreateModel(
            name='StackedInlineExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('field1', models.CharField(blank=True, max_length=50)),
                ('choice', models.CharField(choices=[(b'choice1', b'Choice 1'), (b'choice2', b'Choice 2')], max_length=20)),
                ('inline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_application.InlineExample')),
            ],
            options={
                'verbose_name': 'Stacked inline example',
                'verbose_name_plural': 'Stacked inline example',
            },
        ),
        migrations.CreateModel(
            name='TabularInlineExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('choice', models.CharField(choices=[(b'choice1', b'Choice 1'), (b'choice2', b'Choice 2')], max_length=20)),
                ('inline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_application.InlineExample')),
            ],
            options={
                'verbose_name': 'Tabular inline example',
                'verbose_name_plural': 'Tabular inline example',
            },
        ),
        migrations.CreateModel(
            name='WidgetsExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autocomplete', models.CharField(help_text=b'This widget suggests values based on other records', max_length=50)),
                ('text_area', models.TextField(blank=True)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('radio_select', models.CharField(choices=[(b'choice1', b'Choice 1'), (b'choice2', b'Choice 2'), (b'choice3', b'Choice 3')], default=b'choice1', max_length=20)),
                ('boolean', models.BooleanField(default=False)),
                ('boolean2', models.BooleanField(default=False, help_text=b'You can change the switch labels, size and colors, like in the fields below.')),
                ('boolean3', models.BooleanField(default=False)),
                ('boolean4', models.BooleanField(default=False)),
                ('foreign_key', models.ForeignKey(blank=True, help_text=b'add dialog opens in fancybox', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk1', to='demo_application.SideBarMenuExample')),
                ('foreign_key2', models.ForeignKey(blank=True, help_text=b'raw_id opens in fancybox as well', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk2', to='demo_application.SideBarMenuExample')),
                ('foreign_key3', models.ForeignKey(blank=True, help_text=b"select2 alternative for foreign keys. This adds a search box to quickly find the records you're looking for.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk3', to='demo_application.SideBarMenuExample')),
                ('multiple_select', models.ManyToManyField(blank=True, help_text=b'<p>Default multiple select with horizontal filtering.</p>', null=True, to='demo_application.SideBarMenuExample')),
                ('multiple_select2', models.ManyToManyField(blank=True, help_text=b'<p>Same as above, but with the Select2MultipleWidget widget.</p><p class="small text-info">The annoying "Hold down Control..." message that django automatically appends to this help text will be at last removed in django 1.6!</p>', null=True, to='demo_application.DragNDropChangelistExample')),
            ],
            options={
                'verbose_name': 'Widgets example',
                'verbose_name_plural': 'Widgets example',
            },
        ),
        migrations.AddField(
            model_name='nestedinlineexample',
            name='popupinline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_application.PopupInlineExample'),
        ),
    ]
